name: flavodish
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  animations: ^2.0.11
  flutter_bloc: ^8.1.6
  cached_network_image: ^3.4.1
  dartz: ^0.10.1
  dio: ^5.7.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.10+1
  get_it: ^8.0.0
  go_router: ^14.3.0
  google_fonts: ^6.2.1
  hugeicons: ^0.0.7
  shimmer: ^3.0.0


dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/images/
    - assets/svg/

  fonts:
    - family: Sofia Pro
      fonts:
        - asset: assets/fonts/Sofia Pro Regular.ttf
