// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt_9h8aDY_wZp2yg-jmuZIjca7r2GFgoo',
    appId: '1:907813462334:web:49d18a72c7f0e167604c6f',
    messagingSenderId: '907813462334',
    projectId: 'flavo-dish',
    authDomain: 'flavo-dish.firebaseapp.com',
    storageBucket: 'flavo-dish.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3p2uZ_AIqtsxRJRKsV_y7AHYyq8n1Jfg',
    appId: '1:907813462334:android:56a0ad507fd3eed3604c6f',
    messagingSenderId: '907813462334',
    projectId: 'flavo-dish',
    storageBucket: 'flavo-dish.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH6lNjX1zN-TA2GujFMAAz4AZVhyMGJQw',
    appId: '1:907813462334:ios:b56f3525f0759b55604c6f',
    messagingSenderId: '907813462334',
    projectId: 'flavo-dish',
    storageBucket: 'flavo-dish.firebasestorage.app',
    iosBundleId: 'com.example.flavodish',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBH6lNjX1zN-TA2GujFMAAz4AZVhyMGJQw',
    appId: '1:907813462334:ios:b56f3525f0759b55604c6f',
    messagingSenderId: '907813462334',
    projectId: 'flavo-dish',
    storageBucket: 'flavo-dish.firebasestorage.app',
    iosBundleId: 'com.example.flavodish',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDt_9h8aDY_wZp2yg-jmuZIjca7r2GFgoo',
    appId: '1:907813462334:web:fec25b84a08678e7604c6f',
    messagingSenderId: '907813462334',
    projectId: 'flavo-dish',
    authDomain: 'flavo-dish.firebaseapp.com',
    storageBucket: 'flavo-dish.firebasestorage.app',
  );
}
